layout_spectrum: 0.5456677
typography_spectrum: 0.4329084
color:
  lightness: 0.1338447
  brandStrength: 0.2554806
  saturation: 0.8222282
  rhythmicContrast: 0.6032046
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: Nomami Arquitectos
