typography_spectrum: 0.4329084
color:
  lightness: 0.1804384
  brandStrength: 0.2554806
  saturation: 0.3086003
  rhythmicContrast: 0.6032046
layout_spectrum: 1
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6e8d5f55-a5f0-4cc5-86f3-fdec6bdeff7c.jpg
name: Nomami Arquitectos
title: work
