layout_spectrum: 0.5042158
author:
  url: www.nomami.es
  name: Miguel Santiago
  email: info@nomami.es
title: work
name: Nomami Arquitectos
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0
color:
  brandStrength: 0.5311973
  lightness: 0.6416526
  saturation: 0.3086003
  rhythmicContrast: 0.6032046
  brandColors:
    - '#0F201C'
    - '#3D5144'
    - '#F2E86B'
    - '#E2BC43'
    - '#819274'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6e8d5f55-a5f0-4cc5-86f3-fdec6bdeff7c.jpg
